# Root path-related information and control flags are in uppercase, other info in lowercase

[HOME]

name = 'Your Name'

about_me = [
    "I am ...",
    "Currently, ..."
]
about_website = [
    "This Website is used to ...",
    "..."
]

email = "none"
# Only GitHub username
github = "none"
# Only X (formerly Twitter) username
x = "none"

# Changing this will currently cause an error
PATH = "./webroot/index.html"

[RESUME]
# If you want to undisplay this, goto _kernel/html-template/index.html

PATH = './webroot/assets/resume.pdf'

[DOWNLOAD]

PATH.INDEX = "./webroot/assets/download.html"
PATH.RESOURCE = "./webroot/assets/download/"

[BLOG]
# Where to place the markdown source files
PATH.MD = "./user/blog/"
# Where to place the source files for reprints, including lists and notes
PATH.ONLINE = "./user/blog_online/"
# Where to store the generated web pages
PATH.WEB = "./webroot/blog/"
# Where to store the blog index page
PATH.INDEX = "./webroot/blog.html"
# Where to store the redirect files
# Changing this may cause errors
PATH.REDIRECT = "./webroot/assets/redirect-page/"

# Blog index page layout:
# header      |  toc
# description |
# content     |

# Whether to generate a table of contents (toc) in the blog index page
INDEX.TOC = true
# Blog index page header text
INDEX.header = "Notes"
# Blog index page description
INDEX.description = "This page and the following HTML-type web pages are all built by the automatic generator in this repository. The corresponding markdown source files of these HTML-type web pages can be found in the repository."

[OTHER]

PATH = './webroot/assets/other.html'

[COMPILE]
# Toggle debug mode
DEBUG = false